"use client";

import { FormEvent, useEffect, useState } from "react";
type Book={title:string;author:string;genre:string;pages:number;reason:string;library:string;available:boolean;color:string};
type LiveBook={title:string;author:string;publisher:string;year:string;isbn:string;category:string;detailUrl:string};
type SelectedBook={title:string;author:string;publisher?:string;year?:string;isbn?:string;category?:string;detailUrl?:string;reason?:string;library?:string;available?:boolean;pages?:number};
const books:Book[]=[
{title:"칵테일, 러브, 좀비",author:"조예은",genre:"한국소설",pages:168,reason:"짧고 선명한 이야기가 필요한 저녁에",library:"부산시립시민도서관",available:true,color:"#ff6b51"},
{title:"아주 희미한 빛으로도",author:"최은영",genre:"한국소설",pages:352,reason:"조용히 오래 남는 문장을 읽고 싶을 때",library:"부산시립시민도서관",available:false,color:"#3867f4"},
{title:"이처럼 사소한 것들",author:"클레어 키건",genre:"외국소설",pages:132,reason:"한 호흡에 읽고 깊은 여운을 남기고 싶을 때",library:"명장도서관",available:true,color:"#7d4be2"},
{title:"물고기는 존재하지 않는다",author:"룰루 밀러",genre:"과학·에세이",pages:300,reason:"예상 못 한 지적 반전을 만나고 싶을 때",library:"부산시립시민도서관",available:true,color:"#0f9476"},
{title:"어서 오세요, 휴남동 서점입니다",author:"황보름",genre:"한국소설",pages:364,reason:"마음을 천천히 정돈하는 독서가 필요할 때",library:"안락누리도서관",available:true,color:"#e99d17"}];
const moods=["몰입하고 싶어","마음이 복잡해","기분 전환","새로운 걸 알고 싶어"];
export default function BookFinder(){
const[mood,setMood]=useState(moods[0]);const[minutes,setMinutes]=useState("60");const[result,setResult]=useState(books.slice(0,3));const[searched,setSearched]=useState(false);const[liveBooks,setLiveBooks]=useState<LiveBook[]>([]);const[loading,setLoading]=useState(false);const[liveError,setLiveError]=useState("");const[selectedBook,setSelectedBook]=useState<SelectedBook|null>(null);
useEffect(()=>{if(!selectedBook)return;const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setSelectedBook(null)};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[selectedBook]);
async function recommend(e:FormEvent){e.preventDefault();const rotated=mood===moods[3]?[books[3],books[2],books[0]]:mood===moods[1]?[books[4],books[1],books[2]]:books.slice(0,3);setResult(rotated.filter(b=>minutes==="30"?b.pages<200:true));setSearched(true);setLoading(true);setLiveError("");const moodKey=mood===moods[3]?"learn":mood===moods[1]?"calm":mood===moods[2]?"refresh":"focus";try{const r=await fetch(`/api/recommendations?mood=${moodKey}`);if(!r.ok)throw new Error();const d=await r.json();setLiveBooks(d.books??[])}catch{setLiveError("국립중앙도서관 검색 결과를 불러오지 못했어요.")}finally{setLoading(false)}}
return <main><header className="topbar"><a className="brand" href="#top" aria-label="오늘 뭐 빌리지 홈"><span className="brand-mark" aria-hidden="true">책</span><span>오늘 뭐 <strong>빌리지?</strong></span></a><div className="location"><span aria-hidden="true">●</span> 부산 사직동</div></header>
<section className="workspace" id="top"><div className="intro"><p className="kicker">사직동에서 오늘 읽을 한 권</p><h1>어떤 하루를<br/>보내고 있나요?</h1><p>기분과 남은 시간을 고르면, 가까운 도서관에서 빌릴 만한 책을 골라드려요.</p></div><form className="finder" onSubmit={recommend}><fieldset><legend><span>1</span> 지금 기분은?</legend><div className="chips">{moods.map(x=><button type="button" className={mood===x?"chip active":"chip"} onClick={()=>setMood(x)} key={x}>{x}</button>)}</div></fieldset><fieldset><legend><span>2</span> 얼마나 읽을까요?</legend><div className="time-options">{[{v:"30",t:"잠깐",s:"30분 안쪽"},{v:"60",t:"한 시간",s:"차 한 잔과 함께"},{v:"long",t:"푹 빠져서",s:"시간 제한 없이"}].map(x=><label className={minutes===x.v?"time active":"time"} key={x.v}><input type="radio" name="minutes" checked={minutes===x.v} onChange={()=>setMinutes(x.v)}/><strong>{x.t}</strong><small>{x.s}</small></label>)}</div></fieldset><button className="submit">오늘의 책 골라줘 <span>→</span></button><p className="demo-note">추천을 누르면 국립중앙도서관의 실제 자료를 함께 검색해요.</p></form></section>
<section className="results" aria-live="polite"><div className="results-head"><div><p className="kicker">TODAY&apos;S PICKS</p><h2>{searched?"다시 골라봤어요":"오늘은 이 책 어때요?"}</h2></div><span>{result.length}권 추천</span></div><div className="book-grid">{result.map((b,i)=><button type="button" className="book" key={b.title} onClick={()=>setSelectedBook({title:b.title,author:b.author,category:b.genre,pages:b.pages,reason:b.reason,library:b.library,available:b.available})} aria-label={`${b.title} 상세보기`}><span className="cover" style={{background:b.color}}><span>{b.genre}</span><b>{b.title}</b><small>{b.author}</small><i>{String(i+1).padStart(2,"0")}</i></span><span className="book-info"><span className="book-reason">{b.reason}</span><span className="meta"><span>{b.pages}쪽</span><span>{b.genre}</span></span><span className="availability"><span className={b.available?"dot on":"dot"}/><span><strong>{b.library}</strong><small>{b.available?"대출 가능":"현재 대출 중"}</small></span></span></span></button>)}</div></section>
{(loading||liveBooks.length>0||liveError)&&<section className="live-results"><div className="live-heading"><div><p className="kicker">NATIONAL LIBRARY DATA</p><h2>이 기분으로 찾은 실제 소장자료</h2></div><span>6권 추천 · 국립중앙도서관</span></div>{loading&&<div className="loading-card">도서관 자료를 검색하는 중…</div>}{liveError&&<p className="live-error">{liveError}</p>}{!loading&&<div className="live-grid">{liveBooks.slice(0,6).map((b,i)=><button type="button" className="live-book" key={`${b.isbn}-${i}`} onClick={()=>setSelectedBook(b)} aria-label={`${b.title} 상세보기`}><span className="rank">{i+1}</span><span><strong>{b.title}</strong><span className="live-author">{b.author}</span><small>{b.publisher}{b.year?` · ${b.year}`:""}</small></span></button>)}</div>}</section>}
{selectedBook&&<div className="modal-backdrop" role="presentation" onMouseDown={(e)=>{if(e.target===e.currentTarget)setSelectedBook(null)}}><section className="book-modal" role="dialog" aria-modal="true" aria-labelledby="book-detail-title"><button type="button" className="modal-close" onClick={()=>setSelectedBook(null)} aria-label="상세창 닫기">×</button><p className="modal-kicker">BOOK RECORD</p><h2 id="book-detail-title">{selectedBook.title}</h2><p className="modal-author">{selectedBook.author}</p><dl><div><dt>분류</dt><dd>{selectedBook.category||"정보 없음"}</dd></div>{selectedBook.publisher&&<div><dt>발행처</dt><dd>{selectedBook.publisher}</dd></div>}{selectedBook.year&&<div><dt>발행연도</dt><dd>{selectedBook.year}</dd></div>}{selectedBook.isbn&&<div><dt>ISBN</dt><dd>{selectedBook.isbn}</dd></div>}{selectedBook.pages&&<div><dt>분량</dt><dd>{selectedBook.pages}쪽</dd></div>}{selectedBook.library&&<div><dt>도서관</dt><dd>{selectedBook.library} · {selectedBook.available?"대출 가능":"현재 대출 중"}</dd></div>}</dl>{selectedBook.reason&&<p className="modal-reason">{selectedBook.reason}</p>}{selectedBook.detailUrl&&<a className="detail-link" href={selectedBook.detailUrl} target="_blank" rel="noreferrer">국립중앙도서관에서 상세보기 <span>→</span></a>}</section></div>}
<footer><strong>오늘 뭐 빌리지?</strong><p>도서관 가는 길이 조금 더 설레도록.</p><span>자료 검색 · 국립중앙도서관</span></footer></main>}
